### ISSUE TITLE
How does pyfasttext handle sentence inputs?

### ISSUE THREAD

**Issue by nsanthanam** [vrasneur/pyfasttext#15]
Hi Vincent,

I had a question about how `pyfasttext` handles inputs - how do you process sentences, as opposed to individual tokens? For instance, do I need to separately tokenise my input text, or can I provide it without any preprocessing? From my initial attempts it appears that I can, but since you don't mention it your documentation (which is great, by the way), I wasn't sure.

Thank you for creating this package!

**Comment by vrasneur** [comment]
Hi Navaneethan,

You should have a look at the Dictionary::readWord() method in the fastText source code.

https://github.com/facebookresearch/fastText/blob/ebbd3bfee59a319813214a5c50d7fabe8fb1e344/src/dictionary.cc#L193

You can see that fastText splits words by space (' ', '\t', \r', '\n'\, '\f', '\v', ...).

For example, if you want to separate punctuation from the actual words, you will need to preprocess the data before.

**Comment by nsanthanam** [comment]
I see, thank you for the quick response. I'm less concerned about punctuation at this point, and more about whether I'm getting the representation of the entire sentence, including words that are out-of-vocabulary. This would mean that I will be able to automatically get character n-grams for OOV words (such as phone numbers, which are a series of random numbers), correct?

**Comment by whiletruelearn** [comment]
@nsanthanam @nsanthanam  Interesting discussion . I am also curious on the related topic. 

I see that in fasttext documentation, it is mentioned that sentence vector representations are available only when model is trained as supervised. 

> If you want to compute vector representations of sentences or paragraphs, please use:

` ./fasttext print-sentence-vectors model.bin < text.txt`

Is there any way to get this functionality as we have currently for 

` model.get_numpy_vector("word")`

Or can something like ` model.get_numpy_vector("the quick brown fox jumps over the dog")` give me the vector representation for the sentence correctly ?

**Comment by vrasneur** [comment]
From what I understand, fastText has internal methods to output vectors for:
* all the ngrams in a word -> `FastText::ngramVectors()`
* all the sentences in a text (separated by newlines) -> `FastText::textVectors()` (supervised) or `FastText::sentenceVectors()` (unsupervised)

`ngramVectors()` and `sentenceVectors()` use subwords (i.e. ngrams) , but not `textVectors()` because supervised models did not use subwords until... yesterday.

You can see that there is a very recent commit in fastText (https://github.com/facebookresearch/fastText/commit/ebbd3bfee59a319813214a5c50d7fabe8fb1e344) where they have added support for subwords in supervised learning.

Anyway, the module does not currently export these methods because they output the vector to `stdout` instead of returning it as a `std::vector`.

But it would be easy to reimplement these...

**Comment by whiletruelearn** [comment]
@vrasneur Thanks for explaining. 

So `model.get_numpy_vector` gets the output from `FastText::ngramVectors()` always?

**Comment by vrasneur** [comment]
No, `FastText::ngramVectors()` outputs a vector for *each* subword in a word.

When you use the `model.get_numpy_vector()`, this calls `FastText::getVector()` which outputs a single vectors for all the subwords.

**Comment by nsanthanam** [comment]
Interesting - so does `FastText::getVector()` combine the subwords in some way (average, sum, etc.) to give you a vector for the word? And are different word vectors combined to provide a sentence representation?

By the way, thanks for being so patient with your responses - really appreciate it!

**Comment by vrasneur** [comment]
Yes, I will just copy the source code:

```c++
void FastText::getVector(Vector& vec, const std::string& word) const {
  const std::vector<int32_t>& ngrams = dict_->getSubwords(word);
  vec.zero();
  for (auto it = ngrams.begin(); it != ngrams.end(); ++it) {
    if (quant_) {
      vec.addRow(*qinput_, *it);
    } else {
      vec.addRow(*input_, *it);
    }
  }
  if (ngrams.size() > 0) {
    vec.mul(1.0 / ngrams.size());
  }
}
```

You can see that the subword vectors sum is divided by the number of subwords.
So, yes, the vector is averaged :-)

**Comment by whiletruelearn** [comment]
@vrasneur 

I had just one other doubt . What would happen when i pass two words to `model.get_numpy_vector("hello world")` ?

would it sum up the averaged vector for 'hello' and 'world'  . Or will we treat 'hello world' as one word and try to find subwords for it :thinking:

**Comment by vrasneur** [comment]
I have implemented a new method `model.get_subwords()`, so you can see what are the "subwords" in a word.

If I want the subwords of a word using the new language identification model (here: https://fasttext.cc/docs/en/language-identification.html#content):

```py
>>> from pyfasttext import FastText
>>> model = FastText('lid.176.ftz')
>>> model.get_substrings('hello') 
['hello',
 '<h',
 '<he',
 '<hel',
 'he',
 'hel',
 'hell',
 'el',
 'ell',
 'ello',
 'll',
 'llo',
 'llo>',
 'lo',
 'lo>',
 'o>']
```

So, you have the word itself, and all the word ngrams of length 2 to 4 (because the model was trained with the hyperparameters "minn=2" and "maxn=4").

'<' means "beginning of a word", '>' means "end of a word".

If you have spaces in your word, fastText  does not split words before:
```py
>>> from pyfasttext import FastText
>>> model = FastText('lid.176.ftz')
>>> model.get_substrings('hello world')
['hello world', '<h', '<he', '<hel', 'he', 'hel', 'hell', 'el', 'ell', 'ello', 'll', 'llo', 'llo ', 'lo', 'lo ', 'lo w', 'o ', 'o w', 'o wo', ' w', ' wo', ' wor', 'wo', 'wor', 'worl', 'or', 'orl', 'orld', 'rl', 'rld', 'rld>', 'ld', 'ld>', 'd>']
```

So, you will have spaces in your ngrams.

**Comment by whiletruelearn** [comment]
Thank you very much. This will come in handy.
